GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is my event",
  "date": "2020-01-01T00:00:00",
  "price": 100
}

###
@eventId = {{createEvent.response.body.id}}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is my event",
  "date": "2020-01-01T00:00:00",
  "price": 300
}

###
DELETE  http://localhost:3000/events/b2451560-8135-4dee-a98c-200d813cf34e

###
GET http://localhost:3000/events/{{eventId}}/spots/

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A3"
}

###
@spotID = {{createSpot.response.body.id}}
@spotName = {{createSpot.response.body.name}}

DELETE http://localhost:3000/events/{{eventId}}/spots/{{spotID}}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json
X-Api-Token: 1234

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}